#! /usr/bin/bash
: <<'Comment'
awk 'BEGIN { FS= ":" }
{
    print $5
}
END {}' /etc/passwd
Comment

: <<'comment'
awk 'BEGIN { FS= ":"; OFS= "|"; line_number=1 }
{
    print line_number++, $1, $5, $6
}
END {}' /etc/passwd
comment

: <<'Comment'
awk 'BEGIN {FS= ":"; OFS= "|"; line_number=1}
{
    if ($3 >= 500) {
        print line_number++, $1, $3, $5
    }
}
END {}' /etc/passwd
Comment

: << 'X'
awk 'BEGIN {FS= ":"; OFS= "|"; line_number=1}
{
    if ($3 == 500) {
        print line_number++, $1, $3, $5
    }
}
END {}' /etc/passwd
X
: <<'Comment'
awk 'BEGIN {}
{
    if (NR >= 5 && NR <= 15) {
        print $0
    }
}
END {}' /etc/passwd
Comment
: <<'#'
awk 'BEGIN {i=1; FS= ":"}
{
    i=1;
    while (i <= NF) {
        if ($i == "lp") {
            $i = "mylp"
        }
        i++;
    }
    print $0
}
END {}' /etc/passwd
#

: <<'#'
awk 'BEGIN {FS= ":"; max=0}
{
    if ($3 > max) {
        max = $3
    }
}
END { print " Max is " max }' /etc/passwd
#

awk 'BEGIN {FS= ":"; sum=0}
{
    sum += $3;
}
END { print "Sum is " sum}' /etc/passwd